/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/tracking/verbose 1

/tracking/storeTrajectory 0
/tracking/discardParticleTrajectory opticalphoton
/tracking/discardParticleTrajectory e-

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config11.geo"
/rat/db/load ANNIE/ANNIE_AmBesource_d4.geo

/run/initialize

/process/activate Cerenkov all
/glg4scint/on
#/glg4scint/reemission on
#/process/inactivate eBrem

#/process/inactivate deexcitation # doesn't work
#/process/em/deexcitation World false false false
#/process/em/fluo false
#/process/em/auger false
#/process/em/augerCascade false
#/process/em/pixe false
#/process/em/deexcitationIgnoreCut true

#/process/inactivate DeferTrackProc all
#/process/activate DeferTrackProc gamma
#/process/activate DeferTrackProc e+
#/process/activate DeferTrackProc e-

# initialize the visualizer
#/vis/open OGLIQt 10000
#/vis/scene/create

#/vis/scene/add/volume
#/vis/scene/add/trajectories
#/vis/viewer/reset
#/vis/viewer/set/style surface
#/vis/drawVolume

#/vis/viewer/set/viewpointThetaPhi 20 20
#/vis/viewer/set/viewpointVector 0.1 0.2 1.0
#/vis/viewer/set/viewpointVector -0.5 0.1 0.1
#/vis/viewer/zoom 3
#/vis/viewer/pan 0.5 -4.0 m  # this finally works !
#/vis/viewer/set/upVector 0 1 0

#####################
# BEGIN EVENT LOOP

/rat/proc simpledaq
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid
/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"
/rat/procset prune "mc.track:e-"

# Use IO.default_output_filename
/rat/proclast outroot

# AmBe source w/ defined neutron activity
#/generator/add ambe regexfill
#/generator/pos/set AmBe_source

# AmBe source w/ 60 keV gammas
/generator/add combo gun:regexfill
/generator/pos/set AmBe_source # fills AmBe_source volume!! neat!!
/generator/vtx/set gamma 0 0 0 0.060 # 60 keV gammas
#/generator/vtx/set gamma 0 0 0 4.43 # 4.43 MeV gammas
#/generator/vtx/set neutron 0 0 0 2.5e-8 # thermal neutrons

#/generator/add combo gun:point
#/generator/pos/set 0 -133.3 1724 #center of tank
#/generator/vtx/set neutron 0 0 0 2.5e-8 # thermal neutrons

#/generator/pos/set 0 -133.3 1724 #center of tank
#/generator/add combo gun:point
#/generator/pos/set ^detector*|^ncv*

/run/beamOn 100000

#END EVENT LOOP
#####################

#/vis/viewer/refresh
#/vis/viewer/flush

